#!/bin/ksh

export PATH=/usr/sbin:$PATH
export to=zht@ele.me  #delimiter "," if multiple recipients

. ~/.profile
cd /Users/ada/projects/abn_order2

log_file=log/`date +\%Y\%m\%d`.log
./run.ksh > $log_file 2>&1
./sendlog.py $log_file
